Repository Miragon/miranum, pull requests merged in 2024-07, with the labels that each got.

#407 chore: add usertask element template
  examples/inquiry-integration-service/src/main/resources/processes/bpmn/inquery-process.bpmn
  examples/inquiry-integration-service/src/main/resources/processes/element-templates/basis-usertask.json
Labels: chore

#413 fix: add issue templates
  .github/ISSUE_TEMPLATE/1_bug_report.md
  .github/ISSUE_TEMPLATE/2_feature_request.md
Labels: bug

#414 fix(element-template): add asyncBefore and asyncAfter property
  connect/templates/README.md
  connect/templates/camunda7/src/main/java/io/miragon/miranum/connect/elementtemplate/c7/Camunda7ElementTemplateGenerator.java
  connect/templates/camunda7/src/test/java/io/miragon/miranum/connect/elementtemplates/c7/Camunda7ElementTemplateGeneratorTest.java
  connect/templates/camunda7/src/test/resources/expected-test-element-template-no-input-and-output.json
  connect/templates/camunda7/src/test/resources/expected-test-element-template-with-annotated-input-properties.json
  connect/templates/camunda7/src/test/resources/expected-test-element-template-with-named-input-values.json
  connect/templates/camunda7/src/test/resources/expected-test-element-template-with-version.json
  connect/templates/camunda7/src/test/resources/expected-test-element-template.json
  connect/templates/generator-maven-plugin-core/src/main/java/io/miragon/miranum/connect/elementtemplate/core/Camunda7Configuration.java
  connect/templates/generator-maven-plugin/src/main/java/io/miragon/miranum/connect/elementtemplate/Camunda7ConfigImpl.java
  connect/templates/generator-maven-plugin/src/main/java/io/miragon/miranum/connect/elementtemplate/ElementTemplateGeneratorMojo.java
  connect/templates/generator-maven-plugin/src/main/java/io/miragon/miranum/connect/elementtemplate/ElementTemplateGeneratorsFactory.java
  connect/templates/generator-maven-plugin/src/main/java/io/miragon/miranum/connect/elementtemplate/PlatformSpecificConfig.java
  connect/templates/generator-maven-plugin/src/test/java/io/miragon/miranum/connect/elementtemplate/ElementTemplateGeneratorMojoTest.java
  examples/inquiry-integration-service/pom.xml
  examples/inquiry-integration-service/src/main/resources/processes/bpmn/.camunda/element-templates/send-offer.json
  examples/inquiry-integration-service/src/main/resources/processes/bpmn/inquery-process.bpmn
  examples/inquiry-integration-service/src/main/resources/processes/element-templates/service/send-offer.json
  examples/inquiry-integration-service/src/main/resources/processes/element-templates/service/send-rejection.json
  examples/inquiry-integration-service/src/main/resources/processes/element-templates/task/basis-usertask.json
Labels: bug

#415 Feature/tasklist support custom fields
  .run/MiranumPlatformSDU.run.xml
  examples/inquiry-integration-service/src/main/resources/processes/bpmn/inquery-process.bpmn
  examples/inquiry-integration-service/src/main/resources/processes/element-templates/task/basis-usertask.json
  examples/single-deployment-unit-example/src/main/resources/application.yml
  examples/single-deployment-unit-example/src/main/resources/db/migration/postgresql/V05__miranum_task_info.sql
  examples/single-deployment-unit-example/src/main/resources/processes/tasklist-example.bpmn
  examples/single-deployment-unit-example/src/test/resources/tasklist.http
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/TaskProperties.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/TasklistConfiguration.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/adapter/out/task/TaskMapper.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/adapter/out/task/TaskPersistenceAdapter.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/adapter/out/task/taskinfo/TaskCustomFieldEntity.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/adapter/out/task/taskinfo/TaskInfoEntity.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/application/service/TaskInfoService.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/domain/Task.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/domain/TaskCustomFields.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/domain/TaskInfo.java
  platform/engine/task/src/test/java/io/miragon/miranum/platform/tasklist/TaskPropertiesTest.java
  platform/engine/task/src/test/java/io/miragon/miranum/platform/tasklist/adapter/out/task/TaskMapperTest.java
  platform/engine/task/src/test/java/io/miragon/miranum/platform/tasklist/adapter/out/task/TaskOutPortTest.java
  platform/engine/task/src/test/java/io/miragon/miranum/platform/tasklist/application/service/TaskInfoServiceTest.java
  platform/engine/task/src/test/java/io/miragon/miranum/platform/tasklist/application/service/UserTaskQueryImplTest.java
Labels: feature

#416 chore: bump miranum platform version to 0.3.5
  examples/inquiry-integration-service/pom.xml
  examples/single-deployment-unit-example/pom.xml
  platform/pom.xml
Labels: chore

#422 chore: bump connect version
  connect/pom.xml
  examples/inquiry-integration-service/pom.xml
  examples/single-deployment-unit-example/pom.xml
Labels: chore

#427 bugfix: fix get task by id typo
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/application/port/in/UserTaskQuery.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/application/service/UserTaskQueryImpl.java
  platform/engine/task/src/test/java/io/miragon/miranum/platform/tasklist/application/service/UserTaskQueryImplTest.java
Labels: bug

#429 chore: bump miranum platform version to 0.3.6-SNAPSHOT
  examples/inquiry-integration-service/pom.xml
  examples/single-deployment-unit-example/pom.xml
Labels: chore

#430 chore: update dependencies
  connect/core/s3/pom.xml
  connect/coverage/pom.xml
  connect/pom.xml
  connect/templates/generator-maven-plugin/pom.xml
  examples/inquiry-integration-service/pom.xml
  examples/single-deployment-unit-example/pom.xml
  platform/coverage/pom.xml
  platform/deployment/core/receiver-core/pom.xml
  platform/deployment/core/server-core/pom.xml
  platform/deployment/rest/server-rest-starter/pom.xml
  platform/pom.xml
Labels: chore

#432 chore: update maven version to 3.9.8
  connect/templates/generator-maven-plugin/pom.xml
Labels: chore

#433 feat: implement oAuth for Camunda Webapp
  connect/camunda7-remote/all/pom.xml
  connect/camunda7-remote/oauth/src/main/java/io/miragon/miranum/connect/Camunda7oAuthAutoConfiguration.java
  examples/inquiry-integration-service/inquiry.http
  examples/inquiry-integration-service/local.env
  examples/inquiry-integration-service/pom.xml
  examples/inquiry-integration-service/src/main/java/io/miragon/miranum/inquiry/SecurityConfiguration.java
  examples/inquiry-integration-service/src/main/java/io/miragon/miranum/inquiry/adapter/in/rest/InquiryCreateController.java
  examples/inquiry-integration-service/src/main/resources/application.yml
  examples/inquiry-integration-service/src/main/resources/processes/bpmn/inquery-process.bpmn
  examples/single-deployment-unit-example/single-deployment-stack/.env
  examples/single-deployment-unit-example/single-deployment-stack/docker-compose.yml
  examples/single-deployment-unit-example/single-deployment-stack/keycloak/01_initial-realm.yml
  examples/single-deployment-unit-example/single-deployment-stack/keycloak/02_engine.yml
  examples/single-deployment-unit-example/single-deployment-stack/keycloak/03_engine_protocol_mapper.yml
  examples/single-deployment-unit-example/single-deployment-stack/keycloak/03_inquiry.yml
  examples/single-deployment-unit-example/single-deployment-stack/keycloak/04_users.yml
  examples/single-deployment-unit-example/single-deployment-stack/keycloak/05_worker.yml
  examples/single-deployment-unit-example/single-deployment-stack/keycloak/keycloak-changelog.yml
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/CamundaAuthenticationFilterConfiguration.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/CamundaUserAuthenticationFilter.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/GrantedAuthoritiesExtractor.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/TokenParsingOAuth2UserService.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/TokenParsingOidcUserService.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/init/AuthenticationInitializer.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/init/AuthorizationHelper.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/rest/RestExceptionHandler.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/rest/ServiceAccountAuthenticationProvider.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/webapp/OAuthContainerBasedAuthenticationProvider.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/webapp/OAuthIdentityServiceProvider.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/webapp/OAuthLogoutHandler.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/engine/sso/webapp/ReadOnlyIdentityProviderConfiguration.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/database/NoToastPostgresSQLDialect.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/security/SecurityConfiguration.java
  examples/single-deployment-unit-example/src/main/resources/application.yml
  platform/engine/task/pom.xml
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/adapter/in/task/TaskInfoListener.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/application/service/UserTaskQueryImpl.java
  platform/libs/spring-security/spring-security-core/src/main/java/io/miragon/miranum/platform/security/JwtAuthenticationConverter.java
  platform/libs/spring-security/spring-security-core/src/main/java/io/miragon/miranum/platform/security/SpringSecurityProperties.java
  platform/libs/spring-security/spring-security-core/src/main/java/io/miragon/miranum/platform/security/authentication/UserAuthenticationProvider.java
  platform/libs/spring-security/spring-security-core/src/main/java/io/miragon/miranum/platform/security/authentication/UserAuthenticationProviderImpl.java
  platform/libs/spring-security/spring-security-starter/src/main/resources/application-spring-security-starter.yaml
  platform/pom.xml
Labels: feature

#434 chore: bump connect version to 0.7.3
  connect/pom.xml
  examples/inquiry-integration-service/pom.xml
  examples/single-deployment-unit-example/pom.xml
Labels: chore

#435 chore: bump versions platform 0.3.7 connect 0.7.4
  connect/pom.xml
  examples/inquiry-integration-service/pom.xml
  examples/single-deployment-unit-example/pom.xml
  platform/pom.xml
Labels: chore
