Repository Miragon/miranum, pull requests merged in 2024-05, with the labels that each got.

#341 feature(#296): add history plugin
  platform/examples/single-deployment-unit-example/src/main/resources/META-INF/resources/webjars/camunda/app/cockpit/scripts/config.js
  platform/examples/single-deployment-unit-example/src/main/resources/META-INF/resources/webjars/camunda/app/cockpit/scripts/definition-historic-activities.js
  platform/examples/single-deployment-unit-example/src/main/resources/META-INF/resources/webjars/camunda/app/cockpit/scripts/instance-historic-activities.js
  platform/examples/single-deployment-unit-example/src/main/resources/META-INF/resources/webjars/camunda/app/cockpit/scripts/instance-route-history.js
  platform/examples/single-deployment-unit-example/src/main/resources/META-INF/resources/webjars/camunda/app/cockpit/scripts/robot-module.js
Labels: feature

#340 fix: release pipeline
  .github/workflows/release.yml
  .github/workflows/workflow-build-and-release-services.yml
  .github/workflows/workflow-bump-version.yaml
  connect/pom.xml
  platform/engine/core/pom.xml
  platform/examples/single-deployment-unit-example/pom.xml
  platform/pom.xml
Labels: bug

#342 chore: update dependencies
  connect/camunda7-remote/utils/pom.xml
  connect/camunda8/worker/pom.xml
  connect/core/s3/pom.xml
  connect/pom.xml
  connect/templates/generator-maven-plugin/pom.xml
  platform/deployment/core/server-core/pom.xml
  platform/pom.xml
Labels: chore

#344 refactoring(#291): use maven revision for versioning
  .github/workflows/workflow-bump-version.yaml
  connect/camunda7-remote/message/pom.xml
  connect/camunda7-remote/oauth/pom.xml
  connect/camunda7-remote/pom.xml
  connect/camunda7-remote/process/pom.xml
  connect/camunda7-remote/utils/pom.xml
  connect/camunda7-remote/worker/pom.xml
  connect/camunda8/message/pom.xml
  connect/camunda8/pom.xml
  connect/camunda8/process/pom.xml
  connect/camunda8/worker/pom.xml
  connect/core/element-template-api/pom.xml
  connect/core/json/api/pom.xml
  connect/core/json/pom.xml
  connect/core/json/schema-registry/pom.xml
  connect/core/message-api/pom.xml
  connect/core/pom.xml
  connect/core/process-api/pom.xml
  connect/core/s3/pom.xml
  connect/core/shared/pom.xml
  connect/core/task-api/pom.xml
  connect/core/worker-api/pom.xml
  connect/coverage/pom.xml
  connect/pom.xml
  connect/templates/camunda7/pom.xml
  connect/templates/camunda8/pom.xml
  connect/templates/generator-maven-plugin-core/pom.xml
  connect/templates/generator-maven-plugin/pom.xml
  connect/templates/pom.xml
  platform/coverage/pom.xml
  platform/deployment/core/pom.xml
  platform/deployment/core/receiver-core/pom.xml
  platform/deployment/core/server-core/pom.xml
  platform/deployment/examples/embedded-example/pom.xml
  platform/deployment/examples/pom.xml
  platform/deployment/examples/rest-example/pom.xml
  platform/deployment/pom.xml
  platform/deployment/rest/pom.xml
  platform/deployment/rest/receiver-rest-starter/pom.xml
  platform/deployment/rest/server-rest-starter/pom.xml
  platform/deployment/server-embedded-starter/pom.xml
  platform/engine/core/pom.xml
  platform/engine/pom.xml
  platform/engine/task/pom.xml
  platform/engine/user/pom.xml
  platform/examples/pom.xml
  platform/examples/single-deployment-unit-example/pom.xml
  platform/libs/pom.xml
  platform/libs/spring-security/pom.xml
  platform/libs/spring-security/spring-security-core/pom.xml
  platform/libs/spring-security/spring-security-starter/pom.xml
  platform/libs/unit-test/pom.xml
  platform/pom.xml
  pom.xml
Labels: refactoring

#348 chore: update dependencies
  .github/dependabot.yml
  connect/core/json/schema-registry/pom.xml
  connect/pom.xml
  connect/templates/generator-maven-plugin/pom.xml
  platform/deployment/core/receiver-core/pom.xml
  platform/deployment/core/server-core/pom.xml
  platform/examples/single-deployment-unit-example/pom.xml
  platform/pom.xml
Labels: Technical Debt

#361 fix: flatten maven poms
  .gitignore
  connect/pom.xml
  platform/pom.xml
Labels: bug

#364 refactoring: move UseCases and fix auto conf
  connect/camunda7-remote/utils/src/main/java/io/miragon/miranum/connect/camnda7/remote/utils/Camunda7UtilsAutoConfiguration.java
  connect/examples/process-integration-example/src/main/java/io/miragon/miranum/platform/application/StartProcessUseCase.java
  connect/examples/process-integration-example/src/main/java/io/miragon/miranum/platform/application/UserTaskUseCase.java
Labels: feature

#362 fix(miranum): complex object mapping
  connect/camunda7-remote/utils/src/main/java/io/miragon/miranum/connect/camnda7/remote/utils/Camunda7PojoMapper.java
  connect/camunda7-remote/utils/src/test/java/io/miragon/miranum/connect/camnda7/remote/utils/Camunda7PojoMapperTest.java
  connect/camunda7-remote/worker/src/main/java/io/miragon/miranum/connect/camunda7/remote/worker/Camunda7WorkerAdapter.java
  connect/camunda8/message/src/main/java/io/miragon/miranum/connect/adapter/in/c8/message/Camunda8MessageAdapter.java
  connect/core/element-template-api/src/main/java/io/miragon/miranum/connect/elementtemplate/api/PropertyType.java
  connect/core/worker-api/src/main/java/io/miragon/miranum/connect/worker/impl/WorkerAnnotationBeanPostProcessor.java
  connect/core/worker-api/src/main/java/io/miragon/miranum/connect/worker/impl/WorkerExecuteApiImpl.java
  connect/core/worker-api/src/test/java/io/miragon/miranum/connect/worker/impl/impl/WorkerExecuteApiImplTest.java
  connect/templates/camunda7/src/main/java/io/miragon/miranum/connect/elementtemplate/c7/Camunda7ElementTemplateGenerator.java
  connect/templates/camunda8/src/main/java/io/miragon/miranum/connect/elementtemplate/c8/Camunda8ElementTemplateGenerator.java
  platform/examples/single-deployment-unit-example/src/main/resources/application.yml
Labels: bug

#373 feature: move assign task to miranum platform
  .run/MiranumProcessIntegrationExample.run.xml
  connect/examples/process-integration-example/src/main/java/io/miragon/miranum/platform/adapter/in/task/TaskController.java
  connect/examples/process-integration-example/src/main/java/io/miragon/miranum/platform/adapter/in/task/dto/AssignTaskDto.java
  connect/examples/process-integration-example/src/main/java/io/miragon/miranum/platform/adapter/out/miranum/MiranumTaskAdapter.java
  connect/examples/process-integration-example/src/main/java/io/miragon/miranum/platform/application/UserTaskUseCase.java
  connect/examples/process-integration-example/src/main/java/io/miragon/miranum/platform/application/port/in/WorkOnUserTaskInPort.java
  connect/examples/process-integration-example/src/main/java/io/miragon/miranum/platform/application/port/out/WorkOnUserTaskOutPort.java
  platform/engine/task/pom.xml
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/adapter/in/task/TaskController.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/adapter/out/task/miranum/MiranumTaskAdapter.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/application/port/in/WorkOnTaskUseCase.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/application/service/AssignTaskService.java
  platform/engine/task/src/test/java/io/miragon/miranum/platform/tasklist/adapter/in/task/TaskControllerTest.java
  platform/engine/task/src/test/java/io/miragon/miranum/platform/tasklist/adapter/out/miranum/MiranumTaskAdapterTest.java
  platform/engine/task/src/test/java/io/miragon/miranum/platform/tasklist/application/service/AssignTaskServiceTest.java
  platform/examples/single-deployment-unit-example/src/main/resources/taskmanagement.http
Labels: feature
