Repository Miragon/miranum, pull requests merged in 2025-02, with the labels that each got.

#540 chore: clean up stack and remove unused helm charts
  Readme.md
  examples/Readme.md
  examples/single-deployment-unit-example/Readme.md
  examples/stack/.env
  examples/stack/README.md
  examples/stack/docker-compose.yml
  examples/stack/keycloak/01_initial-realm.yml
  examples/stack/keycloak/02_engine.yml
  examples/stack/keycloak/03_inquiry.yml
  examples/stack/keycloak/04_users.yml
  examples/stack/keycloak/keycloak-changelog.yml
  examples/stack/postgres/init.sh
  platform/charts/Readme.md
  platform/charts/miranum-platform/engine-tasklist-service/deployment.yml
  platform/charts/miranum-platform/keycloak/configmap.yml
  platform/charts/miranum-platform/keycloak/deployment.yml
  platform/charts/miranum-platform/keycloak/service.yml
  platform/charts/miranum-platform/namespace.yml
  platform/charts/miranum-platform/postgres/configmap.yml
  platform/charts/miranum-platform/postgres/deployment.yml
  platform/charts/miranum-platform/postgres/service.yml
  platform/charts/miranum-platform/postgres/volume.yml
  platform/charts/miranum-platform/postgres/volume_claim.yml
  platform/platform-stack/README.md
  platform/platform-stack/docker-compose.yml
  platform/platform-stack/keycloak/01_initial-realm.yml
  platform/platform-stack/keycloak/02_engine.yml
  platform/platform-stack/keycloak/03_engine_protocol_mapper.yml
  platform/platform-stack/keycloak/04_users.yml
  platform/platform-stack/keycloak/05_worker.yml
  platform/platform-stack/keycloak/keycloak-changelog.yml
  platform/platform-stack/nginx/nginx.conf
  platform/platform-stack/postgres/init.sh
Labels: chore

#539 feature(#528): usertask notifications
  .run/MiranumPlatformSDU.run.xml
  examples/single-deployment-unit-example/pom.xml
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/adapter/in/miranum/UsertaskNotificationAdapter.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/adapter/out/email/EmailAdapter.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/application/UsertaskNotificationUseCase.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/application/domain/Notification.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/application/domain/SendNotification.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/application/port/in/NotificationInPort.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/application/port/out/SendNotificationOutPort.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/security/SecurityConfiguration.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/CamundaAuthenticationFilterConfiguration.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/CamundaUserAuthenticationFilter.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/GrantedAuthoritiesExtractor.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/TokenParsingOAuth2UserService.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/TokenParsingOidcUserService.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/init/AuthenticationInitializer.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/init/AuthorizationHelper.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/rest/RestExceptionHandler.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/rest/ServiceAccountAuthenticationProvider.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/webapp/OAuthContainerBasedAuthenticationProvider.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/webapp/OAuthIdentityServiceProvider.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/webapp/OAuthLogoutHandler.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/shared/sso/webapp/ReadOnlyIdentityProviderConfiguration.java
  examples/single-deployment-unit-example/src/main/resources/application.yml
  examples/stack/docker-compose.yml
  platform/engine/task/README.md
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/TaskProperties.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/TasklistConfiguration.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/adapter/in/task/TaskListener.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/adapter/out/task/TaskNotificationAdapter.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/application/port/in/TaskNotificationUseCase.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/application/port/out/task/TaskNotificationOutPort.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/application/port/out/task/TaskOutPort.java
  platform/engine/task/src/main/java/io/miragon/miranum/platform/tasklist/application/service/TaskNotificationService.java
  platform/engine/task/src/test/java/io/miragon/miranum/platform/tasklist/adapter/in/task/TaskInfoListenerTest.java
  platform/engine/task/src/test/java/io/miragon/miranum/platform/tasklist/application/service/TaskNotificationServiceTest.java
  platform/engine/user/src/main/java/io/miragon/miranum/platform/user/adapter/mock/UserMockAdapter.java
  platform/engine/user/src/main/java/io/miragon/miranum/platform/user/application/port/in/UserApi.java
  platform/engine/user/src/main/java/io/miragon/miranum/platform/user/application/port/out/UserPort.java
  platform/engine/user/src/main/java/io/miragon/miranum/platform/user/application/service/UserService.java
Labels: feature

#545 fix(ci): refactor maven get version command
  .github/workflows/release.yml
Labels: bug

#548 feat: process engine api
  .run/PlatformStackDev.run.xml
  .run/single-deployment-stack.run.xml
  examples/inquiry-integration-service/inquiry.http
  examples/inquiry-integration-service/pom.xml
  examples/inquiry-integration-service/src/main/java/io/miragon/miranum/inquiry/adapter/in/engine/SendOfferWorker.java
  examples/inquiry-integration-service/src/main/java/io/miragon/miranum/inquiry/adapter/in/engine/SendRejectionWorker.java
  examples/inquiry-integration-service/src/main/java/io/miragon/miranum/inquiry/application/CapacityCheckedUseCase.java
  examples/inquiry-integration-service/src/main/java/io/miragon/miranum/inquiry/application/CustomerMailReceivedUseCase.java
  examples/inquiry-integration-service/src/main/java/io/miragon/miranum/inquiry/application/InquiryReceivedUseCase.java
  examples/inquiry-integration-service/src/main/java/io/miragon/miranum/inquiry/application/OfferCreatedUseCase.java
  examples/inquiry-integration-service/src/main/java/io/miragon/miranum/inquiry/shared/process/AutoDeployProcessesOnStartup.java
  examples/inquiry-integration-service/src/main/java/io/miragon/miranum/inquiry/shared/security/CamundaSecurityConfig.java
  examples/inquiry-integration-service/src/main/java/io/miragon/miranum/inquiry/shared/security/SecurityConfiguration.java
  examples/inquiry-integration-service/src/main/resources/application.yml
  examples/inquiry-integration-service/src/main/resources/processes/bpmn/inquery-process.bpmn
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/adapter/out/email/EmailAdapter.java
  examples/single-deployment-unit-example/src/main/java/io/miragon/miranum/platform/example/adapter/out/email/EmailProperties.java
  examples/single-deployment-unit-example/src/main/resources/application.yml
  examples/single-deployment-unit-example/src/main/resources/processes/tasklist-example.bpmn
Labels: feature

#556 chore: update process-engine-api to 0.4.3
  examples/inquiry-integration-service/pom.xml
Labels: chore
